TECH_PATTERNS = {
    "Stripe": [
        re.compile(r"js\.stripe\.com", re.IGNORECASE),
        re.compile(r"data-stripe", re.IGNORECASE),
        re.compile(r"Stripe\(", re.IGNORECASE),
        re.compile(r"stripe\.js", re.IGNORECASE),
        re.compile(r"stripe\.min\.js", re.IGNORECASE),
        re.compile(r"client_secret", re.IGNORECASE),
        re.compile(r"payment_intent", re.IGNORECASE),
        re.compile(r"stripe-payment-element", re.IGNORECASE),
        re.compile(r"stripe-elements", re.IGNORECASE),
        re.compile(r"stripe-checkout", re.IGNORECASE),
        re.compile(r"stripe__input", re.IGNORECASE),
        re.compile(r"stripe-card-element", re.IGNORECASE),
        re.compile(r"stripe-v3ds", re.IGNORECASE),
        re.compile(r"confirmCardPayment", re.IGNORECASE),
        re.compile(r"createPaymentMethod", re.IGNORECASE),
        re.compile(r"stripePublicKey", re.IGNORECASE),
        re.compile(r"stripe\.handleCardAction", re.IGNORECASE),
        re.compile(r"elements\.create", re.IGNORECASE),
        re.compile(r"js\.stripe\.com/v3/hcaptcha-invisible", re.IGNORECASE),
        re.compile(r"stripe\.createToken", re.IGNORECASE),
        re.compile(r"stripe-payment-request", re.IGNORECASE),
        re.compile(r"stripe__frame", re.IGNORECASE),
        re.compile(r"stripe-checkout\.js", re.IGNORECASE),
        re.compile(r"stripe-payment", re.IGNORECASE),
        re.compile(r"stripe-redirect", re.IGNORECASE),
    ],
    "PayPal": [
        re.compile(r"paypalobjects\.com", re.IGNORECASE),
        re.compile(r"paypal\.Buttons", re.IGNORECASE),
        re.compile(r"data-paypal", re.IGNORECASE),
        re.compile(r"paypal\.js", re.IGNORECASE),
        re.compile(r"paypal-sdk\.js", re.IGNORECASE),
        re.compile(r"paypal-smart-button", re.IGNORECASE),
        re.compile(r"paypal-button", re.IGNORECASE),
        re.compile(r"paypal-checkout-sdk", re.IGNORECASE),
        re.compile(r"paypal-hosted-fields", re.IGNORECASE),
        re.compile(r"paypal-transaction-id", re.IGNORECASE),
        re.compile(r"paypal\.me", re.IGNORECASE),
        re.compile(r"paypal-checkout", re.IGNORECASE),
        re.compile(r"data-paypal-client-id", re.IGNORECASE),
        re.compile(r"paypal\.Order\.create", re.IGNORECASE),
        re.compile(r"paypal-checkout-component", re.IGNORECASE),
        re.compile(r"paypal-funding", re.IGNORECASE),
    ],
    "Razorpay": [
        re.compile(r"checkout\.razorpay\.com", re.IGNORECASE),
        re.compile(r"Razorpay\(", re.IGNORECASE),
        re.compile(r"data-razorpay", re.IGNORECASE),
        re.compile(r"razorpay\.js", re.IGNORECASE),
        re.compile(r"razorpay-checkout", re.IGNORECASE),
        re.compile(r"razorpay-payment-api", re.IGNORECASE),
        re.compile(r"razorpay-sdk", re.IGNORECASE),
        re.compile(r"razorpay-payment-button", re.IGNORECASE),
        re.compile(r"razorpay-order-id", re.IGNORECASE),
        re.compile(r"razorpay\.min\.js", re.IGNORECASE),
        re.compile(r"payment_box payment_method_razorpay", re.IGNORECASE),
        re.compile(r"cdn\.razorpay\.com", re.IGNORECASE),
        re.compile(r"rzp_payment_icon\.svg", re.IGNORECASE),
        re.compile(r"razorpay\.checkout", re.IGNORECASE),
        re.compile(r"data-razorpay-key", re.IGNORECASE),
        re.compile(r"razorpay_payment_id", re.IGNORECASE),
        re.compile(r"razorpay-hosted", re.IGNORECASE),
    ],
    "Braintree": [
        re.compile(r"braintreepayments\.com", re.IGNORECASE),
        re.compile(r"Braintree\.", re.IGNORECASE),
        re.compile(r"js\.braintreegateway\.com", re.IGNORECASE),
        re.compile(r"client_token", re.IGNORECASE),
        re.compile(r"braintree\.js", re.IGNORECASE),
        re.compile(r"braintree-hosted-fields", re.IGNORECASE),
        re.compile(r"braintree-dropin", re.IGNORECASE),
        re.compile(r"braintree-v3", re.IGNORECASE),
        re.compile(r"braintree-client", re.IGNORECASE),
        re.compile(r"braintree-data-collector", re.IGNORECASE),
        re.compile(r"braintree-payment-form", re.IGNORECASE),
        re.compile(r"braintree-3ds-verify", re.IGNORECASE),
        re.compile(r"client\.create", re.IGNORECASE),
        re.compile(r"braintree\.min\.js", re.IGNORECASE),
        re.compile(r"data-braintree", re.IGNORECASE),
        re.compile(r"braintree\.tokenize", re.IGNORECASE),
        re.compile(r"braintree-dropin-ui", re.IGNORECASE),
    ],
    "Adyen": [
        re.compile(r"checkoutshopper-live\.adyen\.com", re.IGNORECASE),
        re.compile(r"adyen\.js", re.IGNORECASE),
        re.compile(r"data-adyen", re.IGNORECASE),
        re.compile(r"adyen-checkout", re.IGNORECASE),
        re.compile(r"adyen-payment", re.IGNORECASE),
        re.compile(r"adyen-components", re.IGNORECASE),
        re.compile(r"adyen-encrypted-data", re.IGNORECASE),
        re.compile(r"adyen-cse", re.IGNORECASE),
        re.compile(r"adyen-dropin", re.IGNORECASE),
        re.compile(r"adyen-web-checkout", re.IGNORECASE),
        re.compile(r"adyen\.encrypt", re.IGNORECASE),
        re.compile(r"checkoutshopper-test\.adyen\.com", re.IGNORECASE),
        re.compile(r"adyen-checkout__component", re.IGNORECASE),
        re.compile(r"adyen-payment-method", re.IGNORECASE),
        re.compile(r"adyen-action", re.IGNORECASE),
        re.compile(r"adyen\.min\.js", re.IGNORECASE),
    ],
    "Authorize.Net": [
        re.compile(r"js\.authorize\.net", re.IGNORECASE),
        re.compile(r"data-authorize", re.IGNORECASE),
        re.compile(r"authorize-payment", re.IGNORECASE),
        re.compile(r"anet\.js", re.IGNORECASE),
        re.compile(r"accept\.authorize\.net", re.IGNORECASE),
        re.compile(r"authorize-hosted-form", re.IGNORECASE),
        re.compile(r"merchantAuthentication", re.IGNORECASE),
        re.compile(r"data-api-login-id", re.IGNORECASE),
        re.compile(r"data-client-key", re.IGNORECASE),
        re.compile(r"Accept\.dispatchData", re.IGNORECASE),
    ],
    "Square": [
        re.compile(r"squareup\.com", re.IGNORECASE),
        re.compile(r"js\.squarecdn\.com", re.IGNORECASE),
        re.compile(r"square\.js", re.IGNORECASE),
        re.compile(r"data-square", re.IGNORECASE),
        re.compile(r"square-payment-form", re.IGNORECASE),
        re.compile(r"square-checkout-sdk", re.IGNORECASE),
        re.compile(r"square\.min\.js", re.IGNORECASE),
        re.compile(r"square-payment-flow", re.IGNORECASE),
        re.compile(r"square\.card", re.IGNORECASE),
        re.compile(r"data-square-application-id", re.IGNORECASE),
        re.compile(r"square\.createPayment", re.IGNORECASE),
    ],
    "Klarna": [
        re.compile(r"klarna\.com", re.IGNORECASE),
        re.compile(r"js\.klarna\.com", re.IGNORECASE),
        re.compile(r"klarna\.js", re.IGNORECASE),
        re.compile(r"data-klarna", re.IGNORECASE),
        re.compile(r"klarna-checkout", re.IGNORECASE),
        re.compile(r"klarna-onsite-messaging", re.IGNORECASE),
        re.compile(r"klarna-payments", re.IGNORECASE),
        re.compile(r"klarna\.min\.js", re.IGNORECASE),
        re.compile(r"klarna-order-id", re.IGNORECASE),
        re.compile(r"klarna-checkout-container", re.IGNORECASE),
        re.compile(r"klarna-load", re.IGNORECASE),
    ],
    "Checkout.com": [
        re.compile(r"js\.checkout\.com", re.IGNORECASE),
        re.compile(r"data-checkout", re.IGNORECASE),
        re.compile(r"checkout-sdk", re.IGNORECASE),
        re.compile(r"checkout-payment", re.IGNORECASE),
        re.compile(r"cko\.js", re.IGNORECASE),
        re.compile(r"checkout\.frames\.js", re.IGNORECASE),
        re.compile(r"cko-payment-token", re.IGNORECASE),
        re.compile(r"checkout\.init", re.IGNORECASE),
        re.compile(r"cko-hosted", re.IGNORECASE),
        re.compile(r"cko-card-token", re.IGNORECASE),
    ],
    "Paytm": [
        re.compile(r"paytm\.js", re.IGNORECASE),
        re.compile(r"data-paytm", re.IGNORECASE),
        re.compile(r"paytm-checkout", re.IGNORECASE),
        re.compile(r"paytm-payment-sdk", re.IGNORECASE),
        re.compile(r"paytm-wallet", re.IGNORECASE),
        re.compile(r"paytm\.allinonesdk", re.IGNORECASE),
        re.compile(r"paytm\.min\.js", re.IGNORECASE),
        re.compile(r"paytm-transaction-id", re.IGNORECASE),
        re.compile(r"paytm\.invoke", re.IGNORECASE),
        re.compile(r"paytm-checkout-js", re.IGNORECASE),
        re.compile(r"data-paytm-order-id", re.IGNORECASE),
    ],
    "Shopify Payments": [
        re.compile(r"data-shopify-payments", re.IGNORECASE),
        re.compile(r"shopify-checkout-sdk", re.IGNORECASE),
        re.compile(r"shopify-payment-api", re.IGNORECASE),
        re.compile(r"shopify-sdk", re.IGNORECASE),
        re.compile(r"shopify-express-checkout", re.IGNORECASE),
        re.compile(r"shopify_payments\.js", re.IGNORECASE),
        re.compile(r"shopify-payment-token", re.IGNORECASE),
        re.compile(r"shopify\.card", re.IGNORECASE),
        re.compile(r"shopify-checkout-api", re.IGNORECASE),
        re.compile(r"data-shopify-checkout", re.IGNORECASE),
    ],
    "Worldpay": [
        re.compile(r"worldpay\.js", re.IGNORECASE),
        re.compile(r"data-worldpay", re.IGNORECASE),
        re.compile(r"worldpay-checkout", re.IGNORECASE),
        re.compile(r"worldpay-payment-sdk", re.IGNORECASE),
        re.compile(r"worldpay-secure", re.IGNORECASE),
        re.compile(r"worldpay\.min\.js", re.IGNORECASE),
        re.compile(r"worldpay\.token", re.IGNORECASE),
        re.compile(r"worldpay-payment-form", re.IGNORECASE),
        re.compile(r"worldpay-3ds", re.IGNORECASE),
        re.compile(r"data-worldpay-token", re.IGNORECASE),
    ],
    "2Checkout": [
        re.compile(r"2co\.js", re.IGNORECASE),
        re.compile(r"data-2checkout", re.IGNORECASE),
        re.compile(r"2checkout-payment", re.IGNORECASE),
        re.compile(r"2co-checkout", re.IGNORECASE),
        re.compile(r"data-2co-seller-id", re.IGNORECASE),
        re.compile(r"2checkout\.convertplus", re.IGNORECASE),
        re.compile(r"2checkout\.token", re.IGNORECASE),
    ],
    "Amazon Pay": [
        re.compile(r"amazonpay\.js", re.IGNORECASE),
        re.compile(r"data-amazon-pay", re.IGNORECASE),
        re.compile(r"amazon-pay-button", re.IGNORECASE),
        re.compile(r"amazon-pay-checkout-sdk", re.IGNORECASE),
        re.compile(r"amazon-pay-wallet", re.IGNORECASE),
        re.compile(r"amazon-checkout\.js", re.IGNORECASE),
        re.compile(r"amazon-pay-token", re.IGNORECASE),
        re.compile(r"amazon-pay-sdk", re.IGNORECASE),
        re.compile(r"data-amazon-pay-merchant-id", re.IGNORECASE),
        re.compile(r"amazon-pay-signin", re.IGNORECASE),
        re.compile(r"amazon-pay-checkout-session", re.IGNORECASE),
    ],
    "Apple Pay": [
        re.compile(r"apple-pay\.js", re.IGNORECASE),
        re.compile(r"data-apple-pay", re.IGNORECASE),
        re.compile(r"apple-pay-button", re.IGNORECASE),
        re.compile(r"apple-pay-checkout-sdk", re.IGNORECASE),
        re.compile(r"apple-pay-session", re.IGNORECASE),
        re.compile(r"apple-pay-payment-request", re.IGNORECASE),
        re.compile(r"ApplePaySession", re.IGNORECASE),
        re.compile(r"apple-pay-merchant-id", re.IGNORECASE),
        re.compile(r"apple-pay-payment", re.IGNORECASE),
        re.compile(r"apple-pay-sdk", re.IGNORECASE),
        re.compile(r"data-apple-pay-token", re.IGNORECASE),
        re.compile(r"apple-pay-checkout", re.IGNORECASE),
        re.compile(r"apple-pay-domain", re.IGNORECASE),
    ],
    "Google Pay": [
        re.compile(r"googlepay\.js", re.IGNORECASE),
        re.compile(r"data-google-pay", re.IGNORECASE),
        re.compile(r"google-pay-button", re.IGNORECASE),
        re.compile(r"google-pay-checkout-sdk", re.IGNORECASE),
        re.compile(r"google-pay-tokenization", re.IGNORECASE),
        re.compile(r"google-pay-token", re.IGNORECASE),
        re.compile(r"google-pay-payment-method", re.IGNORECASE),
        re.compile(r"data-google-pay-merchant-id", re.IGNORECASE),
        re.compile(r"google-pay-checkout", re.IGNORECASE),
        re.compile(r"google-pay-sdk", re.IGNORECASE),
    ],
    "Mollie": [
        re.compile(r"mollie\.js", re.IGNORECASE),
        re.compile(r"data-mollie", re.IGNORECASE),
        re.compile(r"mollie-checkout", re.IGNORECASE),
        re.compile(r"mollie-payment-sdk", re.IGNORECASE),
        re.compile(r"mollie-components", re.IGNORECASE),
        re.compile(r"mollie\.min\.js", re.IGNORECASE),
        re.compile(r"mollie-payment-token", re.IGNORECASE),
        re.compile(r"mollie-create-payment", re.IGNORECASE),
        re.compile(r"data-mollie-profile-id", re.IGNORECASE),
        re.compile(r"mollie-checkout-form", re.IGNORECASE),
        re.compile(r"mollie-redirect", re.IGNORECASE),
    ],
    "Opayo": [
        re.compile(r"opayo\.js", re.IGNORECASE),
        re.compile(r"data-opayo", re.IGNORECASE),
        re.compile(r"opoayo-checkout", re.IGNORECASE),
        re.compile(r"opayo-payment-sdk", re.IGNORECASE),
        re.compile(r"opayo-form", re.IGNORECASE),
        re.compile(r"opayo\.min\.js", re.IGNORECASE),
        re.compile(r"opayo-payment-token", re.IGNORECASE),
        re.compile(r"opayo-3ds", re.IGNORECASE),
        re.compile(r"data-opayo-merchant-id", re.IGNORECASE),
        re.compile(r"opayo-hosted", re.IGNORECASE),
    ],
    "Paddle": [
        re.compile(r"paddle_button\.js", re.IGNORECASE),
        re.compile(r"paddle\.js", re.IGNORECASE),
        re.compile(r"data-paddle", re.IGNORECASE),
        re.compile(r"paddle-checkout-sdk", re.IGNORECASE),
        re.compile(r"paddle-product-id", re.IGNORECASE),
        re.compile(r"paddle\.min\.js", re.IGNORECASE),
        re.compile(r"paddle-checkout", re.IGNORECASE),
        re.compile(r"data-paddle-vendor-id", re.IGNORECASE),
        re.compile(r"paddle\.Checkout\.open", re.IGNORECASE),
        re.compile(r"paddle-transaction-id", re.IGNORECASE),
        re.compile(r"paddle-hosted", re.IGNORECASE),
    ],
    "Shopify": [
        re.compile(r"shopify\.com", re.IGNORECASE),
        re.compile(r"data-shopify", re.IGNORECASE),
        re.compile(r"Shopify\.", re.IGNORECASE),
    ],
    "WooCommerce": [
        re.compile(r"woocommerce", re.IGNORECASE),
        re.compile(r"wp-content/plugins/woocommerce", re.IGNORECASE),
        re.compile(r"wc-ajax", re.IGNORECASE),
    ],
    "Cloudflare": [
        re.compile(r"cloudflare\.com", re.IGNORECASE),
        re.compile(r"cf-ray", re.IGNORECASE),
        re.compile(r"__cf_chl", re.IGNORECASE),
    ],
    "reCaptcha": [
        re.compile(r"g-recaptcha", re.IGNORECASE),
        re.compile(r"recaptcha/api\.js", re.IGNORECASE),
        re.compile(r"data-sitekey", re.IGNORECASE),
        re.compile(r"nocaptcha", re.IGNORECASE),
        re.compile(r"recaptcha\.net", re.IGNORECASE),
        re.compile(r"www\.google\.com/recaptcha", re.IGNORECASE),
        re.compile(r"grecaptcha\.execute", re.IGNORECASE),
        re.compile(r"grecaptcha\.render", re.IGNORECASE),
        re.compile(r"grecaptcha\.ready", re.IGNORECASE),
        re.compile(r"recaptcha-token", re.IGNORECASE),
    ],
    "hCaptcha": [
        re.compile(r"hcaptcha", re.IGNORECASE),
        re.compile(r"assets\.hcaptcha\.com", re.IGNORECASE),
        re.compile(r"hcaptcha\.com/1/api\.js", re.IGNORECASE),
        re.compile(r"data-hcaptcha-sitekey", re.IGNORECASE),
        re.compile(r"hcaptcha-invisible", re.IGNORECASE),
        re.compile(r"hcaptcha\.execute", re.IGNORECASE),
    ],
    "Turnstile": [
        re.compile(r"turnstile", re.IGNORECASE),
        re.compile(r"challenges\.cloudflare\.com", re.IGNORECASE),
        re.compile(r"cf-turnstile-response", re.IGNORECASE),
        re.compile(r"data-sitekey", re.IGNORECASE),
        re.compile(r"__cf_chl_", re.IGNORECASE),
        re.compile(r"cf_clearance", re.IGNORECASE),
    ],
    "Arkose Labs": [
        re.compile(r"arkose-labs", re.IGNORECASE),
        re.compile(r"funcaptcha", re.IGNORECASE),
        re.compile(r"client-api\.arkoselabs\.com", re.IGNORECASE),
        re.compile(r"fc-token", re.IGNORECASE),
        re.compile(r"fc-widget", re.IGNORECASE),
        re.compile(r"arkose", re.IGNORECASE),
        re.compile(r"press and hold", re.IGNORECASE),
        re.compile(r"funcaptcha\.com", re.IGNORECASE),
    ],
    "GeeTest": [
        re.compile(r"geetest", re.IGNORECASE),
        re.compile(r"gt_captcha_obj", re.IGNORECASE),
        re.compile(r"gt\.js", re.IGNORECASE),
        re.compile(r"geetest_challenge", re.IGNORECASE),
        re.compile(r"geetest_validate", re.IGNORECASE),
        re.compile(r"geetest_seccode", re.IGNORECASE),
    ],
    "BotDetect": [
        re.compile(r"botdetectcaptcha", re.IGNORECASE),
        re.compile(r"BotDetect", re.IGNORECASE),
        re.compile(r"BDC_CaptchaImage", re.IGNORECASE),
        re.compile(r"CaptchaCodeTextBox", re.IGNORECASE),
    ],
    "KeyCAPTCHA": [
        re.compile(r"keycaptcha", re.IGNORECASE),
        re.compile(r"kc_submit", re.IGNORECASE),
        re.compile(r"kc__widget", re.IGNORECASE),
        re.compile(r"s_kc_cid", re.IGNORECASE),
    ],
    "Anti Bot Detection": [
        re.compile(r"fingerprintjs", re.IGNORECASE),
        re.compile(r"js\.challenge", re.IGNORECASE),
        re.compile(r"checking your browser", re.IGNORECASE),
        re.compile(r"verify you are human", re.IGNORECASE),
        re.compile(r"please enable javascript and cookies", re.IGNORECASE),
        re.compile(r"sec-ch-ua-platform", re.IGNORECASE),
    ],
    "Captcha": [
        re.compile(r"captcha-container", re.IGNORECASE),
        re.compile(r"captcha-box", re.IGNORECASE),
        re.compile(r"captcha-frame", re.IGNORECASE),
        re.compile(r"captcha_input", re.IGNORECASE),
        re.compile(r"id=\"captcha\"", re.IGNORECASE),
        re.compile(r"class=\"captcha\"", re.IGNORECASE),
        re.compile(r"iframe.+?captcha", re.IGNORECASE),
        re.compile(r"data-captcha-sitekey", re.IGNORECASE),
    ],
}
